### ISSUE TITLE
DistributionNotFound: The 'ruamel.yaml' distribution was not found

### ISSUE THREAD

**Issue by rhysperry111** [M4cs/foxify-cli#2]
Hi, I am trying to submit this as a package to the AUR and it has been going well. The problem is whenever I try to run `foxify` I get this error:
```
Traceback (most recent call last):
  File "/usr/bin/foxify", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3259, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'ruamel.yaml' distribution was not found and is required by foxify-cli
```
Have I missed a dependency?

The AUR package is here: https://aur.archlinux.org/packages/foxify-cli-git/ - you might want to add it to your README

**Comment by rhysperry111** [comment]
Fixed it. You might want to mention the dependencies in the README. I would appreciate it if you mentioned the package in the README
